title: My Website
email: your-email@example.com
description: >-
  A simple Jekyll site.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""      # the base hostname & protocol, e.g. https://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /projects/:slug/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      tags: []
      status: active

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
